### ISSUE TITLE
Threading self._websocket.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})

### ISSUE THREAD

**Issue by s13rw81** [maxBeinlich/yflive#1]
*Greetings*
```python
from yflive import QuoteStreamer
qs = QuoteStreamer()
qs.subscribe(["AAPL", "TSLA"]) 
qs.on_quote = lambda q: print(q)
qs.start()
# unreachable code
print("unreachable code.")
```

After running your code I noticed anything put after `qs.start()` is unreachable till the `ws` is active. I would like to request you kindly see if it will be possible to thread the `self._websocket.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})` so that it can run in the background as a daemon. If possible please also include a mechanism to stop the `ws` after its no more required.

Kindly check [Upstox-API](https://github.com/upstox/upstox-python/blob/35b1509806456cf95484064d4471a7a3f98c63a2/upstox_api/api.py#L313) to see an example. *Thank You.*

**Comment by mbnlc** [comment]
Hello, thanks for bringing this up.

I have looked into `threading` the web socket and it's currently at the top of my list. I'll be sure to notify you once I get it right.

Could you please explain what you mean by:

> unreachable till the ws is active

I feel like your intention was to say "inactive", please correct me if I'm wrong.

As for your second point, there is a mechanism to stop the web socket: `qs.stop()`

https://github.com/mbnlc/yflive/blob/992437c62861617e8c12f3f4af316b06318d1b3c/yflive/streamer.py#L103-L111

This, however, is not very useful until threading is added as the function call could never be reached. If you need a quick fix, I recommend you run `qs.start()` on a new thread like this:

```python
import threading

th = threading.Thread(target=qs.start)
th.start()

print("reachable")
```

This allows you to execute code after establishing a connection. You can also close the connection and thread at any time like this:

```python
qs.stop()
th.join()
```

I don't know what kind of effects this approach might have on error handling and I haven't checked out how this might work for `daemon threads`.

Hope this helps! I'll get to work on implementing threading functionality.

*Cheers*

P.S.: Thanks for pointing me to the Upstox-API

**Comment by s13rw81** [comment]
_Greetings_

Thank your for your prompt reply. Sorry for my poor English but I see you have understood the issue I was trying to point out.

Good luck with your next release.

**Comment by mbnlc** [comment]
Reopening, because issue has not been fixed.

**Comment by mbnlc** [comment]
New version released.
