### ISSUE TITLE
error from callback <function <lambda> at 0x000001D072B928B0>: <lambda>() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by ivbac** [maxBeinlich/yflive#2]
qs = QuoteStreamer()
qs.subscribe(["AAPL", "TSLA"]) 

qs.on_quote = lambda q: print(q)   <------ ???

**Comment by mbnlc** [comment]
Thanks for bringing this to my attention!

Since the last release the callback functions also pass an instance of the QuoteStreamer. I haven't updated the README.md yet.

This should fix your problem:

```python
qs.on_quote = lambda qs, q: print(q)
```

Hope this helps!
