### ISSUE TITLE
Asyncio support?

### ISSUE THREAD

**Issue by ConstantinosM** [maxBeinlich/yflive#4]
Thanks a lot for this very useful module! It works great! I was wondering if there is asyncio support. I also tried the threading option setting to true but this terminated the run without an error (using the sample code you provide in README). Have you tested with multiple stocks and know limitations, how computationally demanding is given an increasing number of subscriptions?

**Comment by mbnlc** [comment]
Hello!

There are currently no plans to add asyncio support. 

The threading feature runs a daemon thread in the background which automatically exits when the program concludes. Try adding a while-loop to keep the program from exiting.

Regarding your second question, I recommend you test the limitations for yourself. This is __NOT__ a professional grade data feed and I don't recommend you use it as such. 

Cheers!

**Comment by ConstantinosM** [comment]
Thank you for your answer! What do you mean when the program concludes? Managing to get let's say one quote?

Sure, I wasn't intending it for professional use but for experimentation. I will try to see how well it does with multiple quotes.

**Comment by mbnlc** [comment]
If you enable should_thread, the streamer is non-blocking, thus it will stop streaming once the program finishes.

**Comment by ConstantinosM** [comment]
Thank you very much!
